name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '10.x', '12.x', '14.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  coverage:
    name: Jest coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_command: npm run test:ci
